deployment:
  image: placeholderUrl
  tag: 0.0.1
  user: 1000
name: frontend
ports: 
  port: 8080
  targetPort: 8080
resources:
  requests:
    cpu: 256m
    memory: 128Mi
  limits:
    cpu: 512m
    memory: 256Mi