apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.config.secret }}"
  labels:
    namespace: "{{ .Values.namespace }}"
type: Opaque
data:
  DB_HOST: "{{ .Values.mongodb.host }}"
  DB_PORT: "{{ .Values.mongodb.port }}"
  MONGODB_USERNAME: "{{ .Values.mongodb.username }}"
  MONGODB_PASSWORD: "{{ .Values.mongodb.password }}"
  MONGODB_DATABASE: "{{ .Values.mongodb.db }}"
  MONGODB_ROOT_PASSWORD: "{{ .Values.mongodb.rootpassword }}"